// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmjotxjabqcycwfxlymq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inptam90eGphYnFjeWN3ZnhseW1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3OTEzODksImV4cCI6MjA1NzM2NzM4OX0.USlSHB3Vehe42WfgaHV4XSJzrZysEO2nwLtqoTLkZZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);